MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Sunfish Hybrid', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('American Eel', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Black Crappie', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Blue Catfish', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Bluegill', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Brown Trout', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Burbot', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Channel Catfish', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Chinook Salmon', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Cutthroat Trout', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Flathead Catfish', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Redfin Pickerel', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Goldeye', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Green Sunfish', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Largemouth Bass', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Muskellunge', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Northern Pike', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Orangespotted sunfish', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Paddlefish', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Pumpkinseed', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Rainbow Trout', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Redear Sunfish', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Rock Bass', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Sauger', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Saugeye', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Shovelnose Sturgeon', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Skipjack Herring', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Smallmouth Bass', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Spotted Bass', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Striped Bass', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Wiper', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Tiger Muskellunge', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('Walleye', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('White Bass', 'test');
MERGE INTO fish (name, scientific_name) KEY(name) VALUES ('White Crappie', 'test');

MERGE INTO users (email, password_hash) KEY(email) VALUES ('test@email.com', 'passwordpassword');
--INSERT INTO trips (location, trip_date, duration_hours, user_id) VALUES ('lake', CURRENT_DATE, 3, (SELECT id FROM users LIMIT 1));
--INSERT INTO catchrecords (length, date_caught, user_id, weight, is_personal_best, fish_id, trip_id) VALUES (22.1, CURRENT_TIMESTAMP, (SELECT id FROM users LIMIT 1), 4.1, true, (SELECT id from fish where name = 'Largemouth Bass' LIMIT 1), (SELECT id from trips LIMIT 1));